### ISSUE TITLE
Dont use yay for everything 

### ISSUE THREAD

**Issue by Brist0l** [davidxmz/LMAE#3]
use pacman instead of yay for installing such as python and all . BTW a really good guide and a pretty concise one too

**Comment by mayaxmz** [comment]
But since yay is sitting over pacman, it still installs the packages from the repos and not the aur. I thought this would make the guide a little easier as you can install everything together. I will wait for the opinion of others and then maybe I will change it.

**Comment by mayaxmz** [comment]
And thank you for your feedback. I appreciate it.

**Comment by Brist0l** [comment]
> But since yay is sitting over pacman, it still installs the packages from the repos and not the aur. I thought this would make the guide a little easier as you can install everything together. I will wait for the opinion of others and then maybe I will change it.

yup . pacman is just _safer_ and it provides maximum compatibility.
